title: Blog Centrale Termica Gratossoglio Missaglia
description: Un Blog Creato per poter informare quelli che vivono nel quartiere a rispeto del storico e situazioni della Centrale Termica Gratossoglio Missaglia.
url: https://igorhmc.github.io/centrale-termica-gratossoglio-missaglia/
baseurl: ""
author:
  name: Igor Castanho
  email: igorhmcastanho@gmail.com
theme: minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _data
  - _includes
  - _layouts
  - _posts
  - _sass
  - assets
  - .gitignore
  - .jekyll-cache
  - .sass-cache
  - .DS_Store
  - node_modules
  - package.json
  - yarn.lock